language: node_js
node_js:
  - "12"
branches:
  only:
    - master
before_deploy:
  - npm run generate
script:
  - echo 'do nothing.'
deploy:
  skip_cleanup: true
  provider: pages
  token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
  fqdn: ray2020.pdis.dev
